import './globals.css'
import { Inter } from 'next/font/google'
import CheckToken from './Component/CheckToken'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Fundoo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
